---
title: "Lab 7 Assignment: Group 21"
format:
  html:
    embed-resources: true
editor: visual
---

------------------------------------------------------------------------

# Group composition

Magdalena Zydorczak, s253712

Parastoo Tabibzadehtehrani, s252800

Sai Renuka Chandrasekaran, s252633

Ole Lennart Decker, s253728

Raquel Ruiz Pascual, s254628

------------------------------------------------------------------------

# Assignment

## Load libraries

## Load data

## Data description

## PCA analysis

### Look at the data in PC coordinates

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE)

pca_fit |> 
  augment(biopsy) 
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#9C0101", benign = "purple")
  ) +
  theme_half_open(12) + background_grid()
  
```

```{r}
pca_fit |> 
  tidy(matrix = "rotation")
```

```{r}
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)


pca_fit |> 
  tidy(matrix = "rotation") |> 
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |> 
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#9C0101"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + 
  theme_minimal_grid(12)
```

### Look at the variance explained by each PC
